"""changing the typo in orders and changes in prices and total_price type

Revision ID: 09d749568ad4
Revises: e1f6a365514c
Create Date: 2024-07-03 12:54:56.141049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09d749568ad4'
down_revision: Union[str, None] = 'e1f6a365514c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('orders', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.drop_column('orders', 'odered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('odered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('orders', 'total_price',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('orders', 'ordered_at')
    # ### end Alembic commands ###
