"""added tracking table

Revision ID: 1cf82a2065a9
Revises: 5a7785e64bf5
Create Date: 2024-07-02 17:24:21.722637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf82a2065a9'
down_revision: Union[str, None] = '5a7785e64bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('odered_date', sa.DateTime(), nullable=False),
    sa.Column('shipment_date', sa.DateTime(), nullable=False),
    sa.Column('delevery_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    op.create_index(op.f('ix_tracking_tracking_id'), 'tracking', ['tracking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_tracking_id'), table_name='tracking')
    op.drop_table('tracking')
    # ### end Alembic commands ###
