"""changed the last and created for users to datetime from int

Revision ID: e1f6a365514c
Revises: 13499d9d1186
Create Date: 2024-07-03 12:51:02.729729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1f6a365514c'
down_revision: Union[str, None] = '13499d9d1186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column('users', sa.Column('created_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'created_date')
    